plugins { id 'com.android.application' }

android {
    namespace 'com.logrit.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.logrit.app'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.0.2'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
    implementation 'com.google.android.gms:play-services-ads:24.6.0'
}
