plugins { id 'com.android.application' }

android {
    namespace 'com.logrit.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.logrit.app'
        minSdk 21
        targetSdk 35
        versionCode 2
        versionName '1.0.0.1'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
